### ISSUE TITLE
在figure中的图片显示不正常

### ISSUE THREAD

**Issue by ldc311** [ldc311/lvzhong#1]
页面：huwai/qijiawu.html
![Screenshot_2020-11-23-10-52-35](https://user-images.githubusercontent.com/64956618/99926721-980bbc80-2d7d-11eb-8d25-2acdbd3f3bac.png)

**Comment by ldc311** [comment]
`        .blog-detail-content img {
            width: 100%;
            margin: 15px 0;
            object-fit: cover;
        }`
去掉width: 100%;，修改为
`        .blog-detail-content img {
            margin: 15px 0;
            object-fit: cover;
        }
`

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
shawnlee000, @RyanNgCT, @raindata5, @zenoscode, @janyin, @antoinegoze, @668, @maxrantil, @privatizer, @GlenCooper, @NickPuljic, @ThinhVu, @Sholanke, @grothedev, @wuyuup, @chZzZzZz, @chr1sp34rse, @tgorskievo, @timvak, @jburd0, @diegogzorrilla, @azd1997, @hrushigawade4, @kevinkoosk, @stefan-vatov, @demethrius20, @J0hnG4lt, @mfer725, @secreter, @hunghn, @lijinghaooo, @Bowuninglu, @geduardcatalindev, @tonye3003, @johnnystack21, @0devcat0, @van010, @jaustingeorge, @mbrotos, @trxo, @AsserHong, @pop000ooo, @hamidra, @colinfeynman, @DrakeWhitehurst, @goodtimelarry, @PlayerYK, @chunngoo23, @adamsaparudin, @oxdc
